# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

oneParallelSum <- function(v) {
    .Call(`_rparallelism_oneParallelSum`, v)
}

oneParallelSumChunked <- function(v, num_cores) {
    .Call(`_rparallelism_oneParallelSumChunked`, v, num_cores)
}

oneParallelSumDeterministic <- function(v, num_cores) {
    .Call(`_rparallelism_oneParallelSumDeterministic`, v, num_cores)
}

oneParallelSumWorker <- function(v) {
    .Call(`_rparallelism_oneParallelSumWorker`, v)
}

rcppParallelSum <- function(v) {
    .Call(`_rparallelism_rcppParallelSum`, v)
}

sum_parallel <- function(vec, num_cores) {
    .Call(`_rparallelism_sum_parallel`, vec, num_cores)
}

